### ISSUE TITLE
i want to tell you sth.

### ISSUE THREAD

**Issue by YMC-GitHub** [tgxhx/node-book-api#1]
it may be good to change `where id = ${id}` into `where id = '${id}'` in files './router/book.js' ,'./router/booklist.js' and  './router/booktitles.js' !

**Comment by tgxhx** [comment]
Thanks for your suggestion, I will fix it.

**Comment by 7utor** [comment]
您好导入的章节有错误，例如择天记，在id285以上都爬取有问题

**Comment by tgxhx** [comment]
@7utor 因为后续章节没有爬取了，你可以自行爬取。
